---
- hosts: all
  become: yes
  tasks:
  - name: "Ansible Fact Hostname : {{ ansible_hostname }}"
    debug: 
      msg: "{{ ansible_hostname }}"
  - name: "Ansible Fact OS : {{ ansible_distribution }}"
    debug: 
      msg: "{{ ansible_distribution }} - {{ ansible_eth0.ipv4.address }}"
      
