---
- hosts: 172.31.12.133
  become: yes
  tasks:
  - name: Install a package  
    yum: name=telnet state=present 
    register: install_output 
  - name: Print Install Output 
    debug: var=install_output
  
